# TODO add config
# TODO check model_type and file name is different

model_type: "phi-2"
model_name: "model"
layers_name: "layers"
module_names:
  - "self_attn.q_proj"
  - "self_attn.k_proj"
  - "self_attn.v_proj"
  - "self_attn.o_proj"
  - "self_attn.dense"
  - "mlp.fc1"
  - "mlp.fc2"
